--- #YAML:1.0
name:               Net-DNS
version:            0.65
abstract:           Perl DNS resolver module
author:
    - Olaf Kolkman <olaf@net-dns.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC_MD5:  1
    Digest::MD5:       2.12
    IO::Socket:        0
    MIME::Base64:      2.11
    Net::IP:           1.2
    Test::More:        0.18
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
